REGIONS = {
    "ABITIBI-TÉMISCAMINGUE": [
        "AMOS", "BELLETERRE", "DUPARQUET", "LA SARRE", "MACAMIC",
        "MALARTIC", "ROUYN-NORANDA", "SENNETERRE", "TÉMISCAMING",
        "VAL-D'OR", "VILLE-MARIE"
    ],
    "BAS-SAINT-LAURENT": [
        "AMQUI", "CAUSAPSCAL", "DÉGELIS", "LA POCATIÈRE", "MATANE",
        "MÉTIS-SUR-MER", "MONT-JOLI", "POHÉNÉGAMOOK", "RIMOUSKI",
        "RIVIÈRE-DU-LOUP", "SAINT-PASCAL", "TÉMISCOUATA-SUR-LE-LAC",
        "TROIS-PISTOLES"
    ],
    "CAPITALE-NATIONALE": [
        "BAIE-SAINT-PAUL", "BEAUPRÉ", "CAP-SANTÉ", "CHÂTEAU-RICHER",
        "CLERMONT", "DONNACONA", "FOSSAMBAULT-SUR-LE-LAC",
        "LAC-DELAGE", "LAC-SAINT-JOSEPH", "LAC-SERGENT",
        "L'ANCIENNE-LORETTE", "NEUVILLE", "PONT-ROUGE", "PORTNEUF",
        "QUÉBEC", "SAINT-AUGUSTIN-DE-DESMAURES", "SAINT-BASILE",
        "SAINTE-ANNE-DE-BEAUPRÉ", "SAINTE-CATHERINE-DE-LA-JACQUES-CARTIER",
        "SAINT-MARC-DES-CARRIÈRES", "SAINT-RAYMOND", "SHANNON"
    ],
    "CENTRE-DU-QUÉBEC": [
        "BÉCANCOUR", "DAVELUYVILLE", "DRUMMONDVILLE", "KINGSEY FALLS",
        "NICOLET", "PLESSISVILLE", "PRINCEVILLE", "VICTORIAVILLE",
        "WARWICK"
    ],
    "CHAUDIÈRE-APPALACHES": [
        "BEAUCEVILLE", "DISRAELI", "LÉVIS", "MONTMAGNY", "SAINTE-MARIE",
        "SAINT-GEORGES", "SAINT-JOSEPH-DE-BEAUCE", "SAINT-PAMPHILE",
        "THETFORD MINES"
    ],
    "CÔTE-NORD": [
        "BAIE-COMEAU", "FERMONT", "FORESTVILLE", "PORT-CARTIER",
        "SCHEFFERVILLE", "SEPT-ÎLES"
    ],
    "ESTRIE": [
        "COATICOOK", "COOKSHIRE-EATON", "DANVILLE", "EAST ANGUS",
        "LAC-MÉGANTIC", "MAGOG", "RICHMOND", "SCOTSTOWN", "SHERBROOKE",
        "STANSTEAD", "VALCOURT", "VAL-DES-SOURCES", "WATERVILLE",
        "WINDSOR"
    ],
    "GASPÉSIE-ÎLES-DE-LA-MADELEINE": [
        "BONAVENTURE", "CAP-CHAT", "CARLETON-SUR-MER", "CHANDLER",
        "GASPÉ", "GRANDE-RIVIÈRE", "MURDOCHVILLE", "NEW RICHMOND",
        "PASPÉBIAC", "PERCÉ", "SAINTE-ANNE-DES-MONTS"
    ],
    "LANAUDIÈRE": [
        "BERTHIERVILLE", "CHARLEMAGNE", "JOLIETTE", "L'ASSOMPTION",
        "LAVALTRIE", "L'ÉPIPHANIE", "MASCOUCHE", "NOTRE-DAME-DES-PRAIRIES",
        "REPENTIGNY", "SAINT-CHARLES-BORROMÉE", "SAINT-GABRIEL",
        "SAINT-LIN-LAURENTIDES", "TERREBONNE"
    ],
    "LAURENTIDES": [
        "BARKMERE", "BLAINVILLE", "BOISBRIAND", "BOIS-DES-FILION",
        "BROWNSBURG-CHATHAM", "DEUX-MONTAGNES", "ESTÉREL", "LACHUTE",
        "LORRAINE", "MIRABEL", "MONT-LAURIER", "MONT-TREMBLANT",
        "PRÉVOST", "RIVIÈRE-ROUGE", "ROSEMÈRE", "SAINT-COLOMBAN",
        "SAINTE-ADÈLE", "SAINTE-AGATHE-DES-MONTS", "SAINTE-ANNE-DES-PLAINES",
        "SAINTE-MARGUERITE-DU-LAC-MASSON", "SAINTE-MARTHE-SUR-LE-LAC",
        "SAINTE-THÉRÈSE", "SAINT-EUSTACHE", "SAINT-JÉRÔME", "SAINT-SAUVEUR"
    ],
    "LAVAL": ["LAVAL"],
    "MAURICIE": [
        "LA TUQUE", "LOUISEVILLE", "SAINT-TITE", "SHAWINIGAN", "TROIS-RIVIÈRES"
    ],
    "MONTRÉAL": [
        "BAIE-D'URFÉ", "BEACONSFIELD", "CÔTE SAINT-LUC", "DOLLARD-DES-ORMEAUX",
        "DORVAL", "HAMPSTEAD", "KIRKLAND", "L'ÎLE-DORVAL", "MONTRÉAL",
        "MOUNT ROYAL", "POINTE-CLAIRE", "SAINTE-ANNE-DE-BELLEVUE",
        "WESTMOUNT"
    ],
    "MONTÉRÉGIE": [
        "ACTON VALE", "BEAUHARNOIS", "BEDFORD", "BELOEIL", "BLAINVILLE",
        "BOUCHERVILLE", "BROMONT", "BROSSARD", "CANDIAC", "CARIGNAN",
        "CHAMBLY", "CHÂTEAUGUAY", "CONTRECOEUR", "COTEAU-DU-LAC",
        "COWANSVILLE", "DELSON", "DUNHAM", "FARNHAM", "GRANBY", "HUDSON",
        "HUNTINGDON", "LAC-BROME", "LA PRAIRIE", "LÉRY", "LONGUEUIL",
        "MARIEVILLE", "MERCIER", "MONT-SAINT-HILAIRE", "NOTRE-DAME-DE-L'ÎLE-PERROT",
        "OTTERBURN PARK", "PINCOURT", "RICHELIEU", "RIGAUD", "SAINT-AMABLE",
        "SAINT-BASILE-LE-GRAND", "SAINT-BRUNO-DE-MONTARVILLE",
        "SAINT-CÉSAIRE", "SAINT-CONSTANT", "SAINTE-CATHERINE",
        "SAINTE-JULIE", "SAINT-HYACINTHE", "SAINT-JEAN-SUR-RICHELIEU",
        "SAINT-JOSEPH-DE-SOREL", "SAINT-LAMBERT", "SAINT-LAZARE",
        "SAINT-MARC-DES-CARRIÈRES", "SAINT-OURS", "SAINT-PHILIPPE",
        "SAINT-PIE", "SAINT-RÉMI", "SAINT-TITE", "SALABERRY-DE-VALLEYFIELD",
        "SOREL-TRACY", "SUTTON", "VAUDREUIL-DORION", "VARENNES",
        "WATERLOO"
    ],
    "NORD-DU-QUÉBEC": ["CHAPAIS", "CHIBOUGAMAU", "LEBEL-SUR-QUÉVILLON", "MATAGAMI"],
    "OUTAOUAIS": ["GATINEAU", "GRACEFIELD", "MANIWAKI", "THURSO"],
    "SAGUENAY-LAC-SAINT-JEAN": [
        "ALMA", "DESBIENS", "DOLBEAU-MISTASSINI", "MÉTABETCHOUAN-LAC-À-LA-CROIX",
        "NORMANDIN", "ROBERVAL", "SAGUENAY", "SAINT-FÉLICIEN"
    ]
}